---

- include: provider-vbox.yml

- name: install OpenSSH server
  apt: pkg='{{item}}' install_recommends=no update_cache=yes cache_valid_time=3600
  with_items:
    - openssh-server

- name: create vagrant user
  user:
    name=vagrant
    comment='vagrant'
    shell=/bin/bash
    state=present
  notify: Change vagrant password

- name: copy vagrant keys
  copy:
    src=home/vagrant/.ssh/
    dest=/home/vagrant/.ssh
    owner=vagrant
    group=vagrant
  notify: Change vagrant password
  
- name: Authorize vagrant key
  authorized_key:
    user=vagrant
    key='{{item}}'
    manage_dir=yes
  with_file:
    - home/vagrant/.ssh/id_rsa.pub
  notify: Change vagrant password

- name: create vagrant sudo
  copy:
    src=etc/sudoers.d/vagrant
    dest=/etc/sudoers.d/vagrant
    owner=root
    group=root
    mode=0640
  notify: Change vagrant password

- name: configure sshd
  lineinfile:
    dest=/etc/ssh/sshd_config
    line='UseDNS no'
    insertafter=EOF
