---

- name: Get installed kernel
  shell:
    ls -1 -X /lib/modules/ | sort -g
  changed_when: False

- name: install virtualbox utils
  apt: pkg='{{item}}' install_recommends=no update_cache=yes cache_valid_time=3600
  with_items:
    - virtualbox-guest-utils
  notify: install virtualbox kernel builders
